project_id = "myuqekgahmislpvmbblm"

[api]
enabled = true
port = 54321

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[functions]
enabled = true
port = 54321

[functions.send-confirmation-email]
verify_jwt = false

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[edge-runtime]
enabled = true
port = 54327