// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myuqekgahmislpvmbblm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15dXFla2dhaG1pc2xwdm1iYmxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNzc3MjEsImV4cCI6MjA2Nzk1MzcyMX0.mM_Xs4muFjpHEcYBolU4MFtXm6VhN9RWSQUdTaqnLTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});